require_relative '../../node_modules/react-native/scripts/react_native_pods'
require_relative '../../node_modules/@react-native-community/cli-platform-ios/native_modules'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'
plugin 'cocoapods-art', :sources => ['onegini']
use_frameworks!

def do_pre_install
  $static_framework = ['Flipper', 'Flipper-Folly','Flipper-RSocket','FlipperKit', 'Flipper-Fmt']
  pre_install do |installer|
    Pod::Installer::Xcode::TargetValidator.send(:define_method,
                                                :verify_no_static_framework_transitive_dependencies) {}
    installer.pod_targets.each do |pod|
      if $static_framework.include?(pod.name)
        def pod.build_type;
          Pod::BuildType.static_library
        end
      end
    end
  end
end

def do_post_install
  use_flipper!({ 'Flipper' => '0.87.0', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1'})
  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        end
    end
  end
end

target 'RNExampleApp' do
  config = use_native_modules!
  use_react_native!(:path => '../../node_modules/react-native')

  pod 'RNCAsyncStorage', :podspec => '../../node_modules/@react-native-async-storage/async-storage'
  pod 'onewelcome-react-native-sdk', :path => '../..'
  
  target 'RNExampleAppTests' do
    inherit! :complete
  end

  do_pre_install
  do_post_install
end

target 'RNExampleApp-tvOS' do
  target 'RNExampleApp-tvOSTests' do
    inherit! :search_paths
  end
end

