require_relative '../../node_modules/react-native/scripts/react_native_pods'
require_relative '../../node_modules/@react-native-community/cli-platform-ios/native_modules'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

plugin 'cocoapods-art', :sources => [
  'onegini'
]

target 'RNExampleApp' do

  config = use_native_modules!

  use_react_native!(:path => '../../node_modules/react-native')

  pod 'RNCAsyncStorage', :podspec => '../../node_modules/@react-native-async-storage/async-storage'
  pod 'onegini-react-native-sdk', :path => '../..'


  target 'RNExampleAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'RNExampleApp-tvOS' do
  # Pods for RNExampleApp-tvOS

  target 'RNExampleApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
